### ISSUE TITLE
Very bright background color

### ISSUE THREAD

**Issue by davidlindero** [Telecommunication-Telemedia-Assessment/avrateNG#10]

**Comment by davidlindero** [comment]
I planned to leave a comment as well;

the background in the testing software is white (or whiteish), it would be great to have it mid-grey (or optional)

**Comment by stg7** [comment]
Hi David,
I added a separate css file and a brief explanation https://github.com/Telecommunication-Telemedia-Assessment/avrateNG#color-scheme

On my todo list is always to change the templates, because they are kind of "outdated", but that has minor priority.

best
Steve

**Comment by davidlindero** [comment]
Works great, thanks! Very appreciated
