### ISSUE TITLE
Anaconda issue

### ISSUE THREAD

**Issue by Weiver23** [Telecommunication-Telemedia-Assessment/avrateNG#4]
When running avrateNG from a fresh anaconda installation, it does not run properly
Workaround: 
with an anaconda virtual environment this issue does not come up.

![sd](https://user-images.githubusercontent.com/23295016/59279983-257c4f00-8c65-11e9-8b3e-00af3c989925.png)

**Comment by stg7** [comment]
related to https://github.com/bottlepy/bottle/issues/1094 , @stg7 checkout current version of bottle if it is probably already fixed

**Comment by stg7** [comment]
seems to be solved based on @rakeshraor checks
